### ISSUE TITLE
EISDIR Illegal operation on directory error

### ISSUE THREAD

**Issue by mattnewham** [SphtKr/homebridge-filesensor#3]
Hey

I think I am doing something silly here but can't figure it out! I have setup my config and the accessory is loaded correctly however home bridge log is just constantly throwing the error:

```
Error: EISDIR: illegal operation on a directory, read
homebridge-1     at Error (native)
homebridge-1     at Object.fs.readSync (fs.js:651:19)
homebridge-1     at Object.fs.readFileSync (fs.js:472:24)
homebridge-1     at Object.LocalStorage.parseDirSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:610:35)
homebridge-1     at Object.LocalStorage.parseDataDirSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:545:21)
homebridge-1     at Object.LocalStorage.initSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:145:14)
homebridge-1     at Object.nodePersist.initSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/node-persist.js:41:29)
homebridge-1     at Object.init (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/index.js:25:13)
homebridge-1     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:24:7)
homebridge-1     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
```

I have set up my file to just point at a file within the persist folder, its definitely full path to the file so I am not sure why it thinks it is a directory.

Any help would be greatly appreciated :)

**Comment by mattnewham** [comment]
Sorted this with a complete reinstall - seems it was a home bridge error
